### ISSUE TITLE
Mechanism for inserting literal braces

### ISSUE THREAD

**Issue by brodieG** [jimhester/fstrings#1]
E.g something like:
```
f('my name is {name}, but do not \\{messwiththis\\}')
```
or (better since less typing and also concordant with what Python does):
```
f('my name is {name}, but do not {{messwiththis}}')
```
wherein the `{{` would get replaced by `{`.

Happy to help with PR if you want help.

**Comment by jimhester** [comment]
The latter is what is already implemented (in that it does not try to interpret `{{`, but does not change the `{{` to `{`, which it probably should.
