### ISSUE TITLE
Add $ Shorthand

### ISSUE THREAD

**Issue by brodieG** [jimhester/fstrings#3]
```
f$"my name is {name}"
```
could work.  Just class `f` and add a `$` method like `gsubfn` does.  Could also provide a different fun to avoid issues (e.g. `F`).

Saves a keystroke and also looks a tiny bit more like the python syntax.

This one is obviously low priority, but kind of cute, and different to the one [I tweeted about](https://twitter.com/BrodieGaslam/status/812458895264333824).

**Comment by briatte** [comment]
Isn't your suggestion a close analog to how [`stringr::str_interp`](https://www.rdocumentation.org/packages/stringr/versions/1.1.0/topics/str_interp) works?

e.g.

```r
library(stringr) # 1.1.0
# Using values from the environment, and some formats
user_name <- "smbache"
amount <- 6.656
account <- 1337
str_interp("User ${user_name} (account $[08d]{account}) has $$[.2f]{amount}.")
```

**Comment by brodieG** [comment]
@briatte, not at all.  Notice the `$` is between the function name and the string.  So the equivalent call in `str_interp` might be `str_interp$"User ${user_name}..."`.  This just avoids having to type the open and close parens (in exchange for the dollar), and looks a little more like the python f strings `f'User {user_name}'`.

**Comment by jimhester** [comment]
This is an interesting suggestion, my only real hesitations are the syntax is different enough from normal R it may be confusing, and the desire to keep this package small and simple.

**Comment by jimhester** [comment]
I have a branch implementing this https://github.com/jimhester/fstrings/tree/f%24#example plus a `+` method, which gives a fairly nice syntax.

However I am not sure the benefits are worth the added complexity, will let it stew a bit, thoughts welcome.

**Comment by brodieG** [comment]
Looks great.  IMO the benefits are worth it, but I also think it would be worth it to allow "$user" to interpolate for the sake of saving a keystroke, so my opinion may not be the best one here.

Nice that you added `+`.  I was thinking of something similar over the weekend, but wanted to play around with it to see if it was possible before proposing it.  I was hoping we could use an operator's `c("missing", "character")` signature to dispatch something like:

```
$"Hello {user}" $ " goodbye {user}"
```
thereby saving yet an other keystroke, but it looks like this can't be done with single character operators.

**Comment by hadley** [comment]
I don't think the trade off is worth it.

**Comment by briatte** [comment]
@brodieG Thanks for the clarification.

Re: trade-off, my impression, FWIW, is that `str_interp` does a fine job at "looking more like Python" here. Furthermore, in

```
f$"my name is {name}"
```

I'm confused by the `$` symbol not meaning "take a piece of `f`".

Perhaps

```
f`User {user_name}`
```

would be even more like Python, but it'd be a complete 'corruption' of what R does with back ticks.

My 2¢.

**Comment by jimhester** [comment]
```
f`User {user_name}`
```
Does not parse.

I agree the trade off is not worthwhile and while this is an interesting idea I don't think it is worth pursuing further.

**Comment by brodieG** [comment]
Thanks for humoring me and exploring anyway.
