### ISSUE TITLE
last (?) argument to collapse

### ISSUE THREAD

**Issue by hadley** [jimhester/fstrings#9]
So you can do:

```R
collapse(1:4, ",", last = ", and ")
#> 1, 2, 3, and 4
```

**Comment by jimhester** [comment]
Oxford comma, surprising hadley!

**Comment by jonocarroll** [comment]
https://github.com/r-lib/cli/issues/128 (for tidy developer day) can be resolved by adding this feature. What do you think about an `oxford = TRUE` for when there are >= 3 arguments? I'm happy to make the PR for that.

**Comment by math-mcshane** [comment]
I thought I had an original idea to introduce an `oxford = TRUE` parameter to `glue_collapse` (presumably the successor to `collapse`). It looks like I wasn't the first. 

If there was a `oxford = TRUE` parameter, AFAIK, it's gone/inaccessible now: 
``` r
glue::glue_collapse(x = 1:4, sep = ", ", last = ", and ")
#> 1, 2, 3, and 4
try(glue::glue_collapse(x = 1:4, sep = ", ", last = " and ", oxford = TRUE))
#> Error in glue::glue_collapse(x = 1:4, sep = ", ", last = " and ", oxford = TRUE) : 
#>   unused argument (oxford = TRUE)
```
I am also not seeing a `collapse` in `cli`, FWIW, just successor functions. 

Signed, pro-Oxford comma guy.
